export const Add_New_QN = 'Add_New_QN'
export const DELETE_QN = 'DELETE_QN'
export const SELEDCT_QN = 'SELEDCT_QN'
export const SELEDCT_QN_ALL = 'SELEDCT_QN_ALL'
export const DELETE_QN_SOME = 'DELETE_QN_SOME'
export const DEAD_LINE_QN = 'DEAD_LINE_QN'
export const TITLEN_QN = 'TITLEN_QN'
export const SUBSTATE_QN = 'SUBSTATE_QN'

/****************QN***************************/
export const ADD_NEW_Q = 'ADD_NEW_Q'
export const DELETE_Q = 'DELETE_Q'
export const TITLEN_Q = 'TITLEN_Q'
export const TEXTN_Q = 'TEXTN_Q'
export const SAVE_QN = 'SAVE_QN'